version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      ENV: ENV
    container_name: flask_test
    volumes:
    - ./:/flask_app
